CREATE TABLE User
(
ID  INTEGER NOT NULL PRIMARY KEY,
type_id INT NOT NULL,
login VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL,
FOREIGN KEY (type_id)
    REFERENCES TypesUsers(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE TypesUsers
(
ID INTEGER NOT NULL PRIMARY KEY,
title VARCHAR(50) NOT NULL,
power_level INT NOT NULL,
);

CREATE TABLE Subjects 
(
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
user_id INT NOT NULL,
name VARCHAR(50) NOT NULL UNIQUE,
FOREIGN KEY (user_id)
    REFERENCES User(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Schedules_of_times_of_subjects
(
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
shedule_id INT NOT NULL,
subject_id INT NOT NULL,
time_id INT NOT NULL,
FORIEGN KEY (shedule_id)
    REFERENCES Shedules(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION 
FOREIGN KEY (subject_id)
    REFERENCES Subjects(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION 
FOREIGN KEY (time_id)
    REFERENCES Times(ID) 
    ON DELETE CASCADE ON UPDATE NO ACTION 
);

CREATE TABLE Shedules
(
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
day_id INT NOT NULL,
note VARCHAR(244) NOT NULL,
FOREIGN KEY (day_id)
    REFERENCES WeekDays(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE WeekDays
(
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
day VARCHAR(50) NOT NULL
);

CREATE TABLE Times 
(
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT;
time VARCHAR(255) NOT NULL;
);









