CREATE TABLE TypesUsers
(
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
title VARCHAR(50) NOT NULL,
power_level INT NOT NULL
);

CREATE TABLE Subjects 
(
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE WeekDays
(
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
day VARCHAR(50) NOT NULL
);

CREATE TABLE Groupss 
(
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
title VARCHAR(50) NOT NULL UNIQUE ,
tutor VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Shedules
(
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
day_id INT NOT NULL,
note VARCHAR(244) NOT NULL,
FOREIGN KEY (day_id)
    REFERENCES WeekDays(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE User
(
ID  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
type_id INT NOT NULL,
login VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL,
group_id INTEGER NOT NULL,
FOREIGN KEY (type_id)
    REFERENCES TypesUsers(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION
FOREIGN KEY (group_id)
    REFERENCES Groupss(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Schedules_of_groupss_of_subjects
(
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
shedule_id INT NOT NULL,
subject_id INT NOT NULL,
group_id INT NOT NULL,
user_id INT NOT NULL,
FOREIGN KEY (shedule_id)
    REFERENCES Shedules(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION 
FOREIGN KEY (subject_id)
    REFERENCES Subjects(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION 
FOREIGN KEY (group_id)
    REFERENCES Groupss(ID) 
    ON DELETE CASCADE ON UPDATE NO ACTION 
FOREIGN KEY (user_id) 
    REFERENCES User(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION    
);















